
resources:
 containers:
   - container: flyway
     image: flyway/flyway-azure:latest-alpine
   - container: schemaspy
     image: schemaspy/schemaspy

jobs:
- job: Example_Database_Build
  timeoutInMinutes: 10
  pool:
    vmImage: ubuntu-16.04
  steps:
  - script: flyway -url='jdbc:sqlserver://$(SERVERNAME):$(PORT_NUMBER);databaseName=$(DATABASENAME);user=$(USER);password=$(PASSWORD);' -user=$(USER) -password=$(PASSWORD) -locations='filesystem:./' migrate
    target: flyway
    name: Run_flyway_migrate
  - task: PowerShell@2
    target: host
    displayName: "Run TSqlT Tests"
    inputs:
      filePath: './RunTests.ps1'
      arguments: -serverName "$(SERVERNAME)" -databaseName "$(DATABASENAME)" -userName "$(USER)" -password "$(PASSWORD)"
  - script: |
      mkdir Output
      chmod -R 777 $PWD/Output
      docker run -v "$PWD/Output:/output" -v "$PWD/DB_Driver:/drivers" schemaspy/schemaspy:latest -t mssql08 -db $(DATABASENAME) -host $(SERVERNAME) -port $(PORT_NUMBER) -u $(USER) -p $(PASSWORD)
    displayName: 'Running schemaspy'
#- script: docker run -v "$PWD:/output" schemaspy/schemaspy:latest -dbhelp
  #displayName: 'Running schemaspy'
  - publish: $(System.DefaultWorkingDirectory)/Output
    artifact: 'DatabaseDocumentation'
  - task: PublishTestResults@2 
    target: host
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'
      testRunTitle: 'Publish_TSqlT_TestResults'
  - publish: $(System.DefaultWorkingDirectory)
    target: flyway
    artifact: 'DatabaseArtifacts'